### ISSUE TITLE
Make a Section for Top Blogging Pages (Bloggers)

### ISSUE THREAD

**Issue by lnxpy** [bobycloud/python-backend-roadmap#5]
A section of top blogging pages for those who might be interested in daily-dose stuff so they can follow the articles and keep the pace with.

**Comment by lnxpy** [comment]
+ You can make a section introducing the top Persian and/or English content creators (video-casts, pod-casts, etc) in the back-end engineering field. :)

**Comment by bobycloud** [comment]
LGTM, Can you send PR dear Sadra?

**Comment by lnxpy** [comment]
Sure. I'm on it.
